# -*- coding: utf-8 -*-
"""colab_basic2_datatypes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SYDM8LtM5VN0DHk_BtXO357zChUwWlrT
"""

a=10
print(type(a))

print(a)

a=float(a)

print(a)

type(a)

x = 3 + 4j
print(x)
#type(x)
print(type(x))

a=True
print(a)
type(a)

a = 7<5
print(a)
type(a)

b = 5<7
print(b)
print(type(b))

print("hello "*5)



"""#slicing in python"""

x = "HelloWorld"
print(x[ : ])

x = "HelloWorld"
print(x[0:5])

x = "HelloWorld"
print(x[0: :3])

x = "HelloWorld"
print(x[ : :-1])

x = "HelloWorld"
print(x[8:0:-1])

#output of palindrome
x = "NITIN"
print(x[::-1])

