# -*- coding: utf-8 -*-
"""colab_Mathplotlib_basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNjHqpxFX9lUJRQ4Pv-xVvphcQU8mPTK

#Useful for making plots/graphs
"""

#importing mathplotlib library
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

x=np.linspace(1,10,100)
print(x)
y=np.sin(x)
z=np.cos(x)
print(y)
print(z)

#plotting the data:
#sine wave
plt.plot(x,y)
plt.show()

#cos wave
plt.plot(x,z)
plt.show()

#x-label and y-label and title on graph
plt.plot(x,y)
plt.xlabel('angles')
plt.ylabel('sine values')
plt.title('sine wave')
plt.show()

#parabola
import numpy as np
x=np.linspace(-10,10,50)
y=x**2
plt.plot(x,y)
plt.show()
plt.plot(x,y,'r+')
plt.show()

plt.plot(x,y,'rx')
plt.show()

x=np.linspace(-5,5,50)
plt.plot(x,np.sin(x),"y+")
plt.plot(x,np.cos(x),"r*")
plt.show()

"""#bar plot"""

fig=plt.figure()   #create empty figure
#plt.show()
ax=fig.add_axes([0,0,1,1])
#plt.show()
language=['english','hindi','spanish','latin','marathi']
people=[100,50,150,40,70]
ax.bar(language,people)
plt.xlabel('language')
plt.ylabel('number of people')
plt.show()

"""#Pie chart"""

fig1=plt.figure()
ax=fig1.add_axes([0,0,1,1])
language=['english','hindi','spanish','latin','marathi']
people=[100,50,150,40,70]
ax.pie(people,labels=language,autopct='%1.2f%%')
plt.show()

"""#scatter plot"""

x=np.linspace(0,10,50)
y=np.sin(x)
z=np.cos(x)
fig2=plt.figure()
ax=fig2.add_axes([0,0,1,1])
ax.scatter(x,y,color='r')
ax.scatter(x,z,color='b')
plt.show()

"""#build 3-D scatter plot"""

fig3=plt.figure()
ax=plt.axes(projection='3d')
z=20*np.random.random(100)
x=np.sin(z)
y=np.cos(z)
ax.scatter(x,y,z,c=z,cmap='Blues')
plt.show()

