# -*- coding: utf-8 -*-
"""colab_module5_matrix_operation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10eYkyHEQk1GYAkuSwooXZCjvkFhit1ue
"""

#working with matrix in python
import numpy as np
matrix_1=np.array([[2,3],[4,5]])
print(matrix_1)
matrix_1.shape

matrix_2=np.array([[2,3,9],[4,5,8],[20,12,32]])
print(matrix_2)
matrix_2.shape

#creating matrix with random values
a=np.random.randint(100,size=(3,4))
print(a)

#creating matrix with zero values (null matrix)
a=np.zeros((3,4))
print(a)

a=np.zeros((3,4),dtype=int)
print(a)

#creating matrix with one value
b=np.ones((3,4),dtype=int)
print(b)

#create identity matrix
c=np.eye(3,4,dtype=int)
print(c)

#transpose of the matrix
a=np.random.randint(100,size=(3,4))
print(a)

b=np.transpose(a)
print(b)

#matrix addition(should be same size)
a=np.array([[2,3],[4,5]])
b=np.array([[4,5],[6,7]])
print(a)
print(b)
a.shape
b.shape

sum=a+b
print(sum)

#matrix addition of two random matrix(should be same size)
a=np.random.randint(100,size=(3,3))
b=np.random.randint(100,size=(3,3))
print(a)
print(b)
a.shape
b.shape

sum=np.add(a,b)
print(sum)

diff=np.subtract(a,b)
print(diff)

#multiplying matrix by scalar
x=5
y=np.random.randint(10,size=(4,3))
print(y)

product=np.multiply(x,y)
print(product)

#multiplication of two matrices (cloumn of first matrix and row of second matrix should be same)
a=np.random.randint(10,size=(4,3))
b=np.random.randint(10,size=(3,3))
print(a)
print(b)
product=np.dot(a,b)
print(product)
product.shape

#element wise multiplication (size of two matrix should be same)
a=np.random.randint(10,size=(3,3))
b=np.random.randint(10,size=(3,3))
print(a)
print(b)
product=np.multiply(a,b)
print(product)
product.shape

