# -*- coding: utf-8 -*-
"""colab_module_45_Label_encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GHE5f_O174HFBMU0yl2bwaUHEE6I5lYN

#label encoding-converting the label into numeric form
"""

#Importing the dependencies
import pandas as pd
from sklearn.preprocessing import LabelEncoder

#label encoding of breast cancer dataset
#load the data from csv file to pandas Dataframe
cancer_data=pd.read_csv('/content/data.csv')
cancer_data.head()

#finding the count of the different labels
cancer_data['diagnosis'].value_counts()

#load the label encoder function
label_encode=LabelEncoder()
labels=label_encode.fit_transform(cancer_data.diagnosis)

#appending the labels to the DataFrame
cancer_data['target']=labels
cancer_data.head()

cancer_data['target'].value_counts()

"""iris datasets"""

#load the data 
iris_data=pd.read_csv('/content/Iris.csv')
iris_data.head()

iris_data['Species'].value_counts()

#load label encoder function
label_encode2=LabelEncoder()
labels=label_encode2.fit_transform(iris_data.Species)

iris_data['target']=labels
iris_data.head()

iris_data['target'].value_counts()

