# -*- coding: utf-8 -*-
"""colab_module_43_method_to_handle_missing_values.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCptOvNtrcUVpmeTeOiFQDcOA38LX0t-
"""

#method to handle missing values
#1)Imputation
#2)Dropping

#importing the libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#loading the dataset to a pandas DataFrame
dataset=pd.read_csv('/content/Placement_Dataset.csv')
dataset.head()

dataset.shape

dataset.isnull().sum()

"""Imputation Method
1) Mean
2) Mode
3) Median
"""

#plot salary column (analysis the distribution od data in the salary column)
fig,ax=plt.subplots(figsize=(8,8))
sns.distplot(dataset.salary)

#this is skew distribution (so we use mode/median method for filling the missing values)
dataset['salary'].fillna(dataset['salary'].median(),inplace=True)

dataset.isnull().sum()

dataset.shape

#dataset['salary'].fillna(dataset['salary'].mode(),inplace=True)

#when values are distributed normally
#dataset['salary'].fillna(dataset['salary'].mean(),inplace=True)

"""#Dropping Method"""

salary_dataset=pd.read_csv('/content/Placement_Dataset.csv')
salary_dataset.shape

salary_dataset.isnull().sum()

#drop missing method
salary_dataset=salary_dataset.dropna(how='any')
salary_dataset.isnull().sum()

salary_dataset.shape

