# -*- coding: utf-8 -*-
"""colab_basic2.4_list_tuple_set_dict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1itdwuzd_NRFQisqRhb2ipuDE7nh2915n

#list
"""

List_1 = [1,2,3,4,5]
print(List_1)
type(List_1)

List_2 = [2,3.4,'hello', True]
print(List_2)

#Add an item from the list
List_3 = [2,3.4,'hello', True, 66]
print(List_3)
List_3.append(7)
print(List_3)

#Add an item from the list
List_4 = [2,3.4,'hello', True, 66]
print(List_4)
List_4.extend('Bye')
print(List_4)

#Delete an item from the list
List_5 = [2,3.4,'hello', True, 66]
print(List_5)
del List_5[2]
print(List_5)

#Join two list (Concatnate the list)
List_6 = [1,2,3,4,5]
List_7 = [6,7,8,9]
List_8 = List_6+List_7
print(List_8)

"""#Tuple"""

my_tuple = (1,2,3,'hello',True)
print(my_tuple)
type(my_tuple)

#converting list in to a tuple
my_list = [1,2,3,4]
print(my_list)
my_tuple2=tuple(my_list)
print(my_tuple2)

print(len(my_tuple2))

print(my_tuple2[3])

"""#Set"""

my_set = {1,2,3,4}
print(my_set)
type(my_set)

#indexing is not possible in set
# print(my_set[1])
#Converting list into set
list_1 = [5,6,7,8]
x = set(list_1)
print(x)

# set does not allow duplicate value

y = {1,2,3,4,5,6,1,2}
print(y)

"""#Dictionary"""

my_dict = {'name':'Litesh', 'age':30, 'company':'COEP'}
print(my_dict)
type(my_dict)

print(my_dict['name'])
print(my_dict['age'])
print(my_dict['company'])

#dictionary does not allow duplicate value
my_dict2 = {'name':'Litesh', 'age':30, 'company':'COEP','name':'Litesh', 'age':30,}
print(my_dict2)

