# -*- coding: utf-8 -*-
"""Numpy_Array_basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o86N-BLpGNU11N9Hizysq5NHG0TbSMMf

# Numpy Tutorial
"""

#using numpy module ---> numpy array is much faster than normal list operation
import numpy as np
from time import process_time
np_array=np.array([i for i in range(500000)])
print(np_array)
start_time = process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

#Using traditional List method (its takes larger time as compare to numpy method)
python_list=[i for i in range(500000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
#print(python_list)
print(end_time-start_time)

#creating a list using numpy array
#normal method
list_1 = [1,2,3,4,5]
print(list_1)
type(list_1)

#using numpy method
np_array=np.array([1,2,3,4,5])
print(np_array)   #created array is similar to the 1-D matrix
type(np_array)
np_array.shape

#creating 2-D array
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a)
a.shape

b=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(b)

"""#Initial placeholder in numpy array"""

#create a numpy array of zeros
x=np.zeros((4,5),dtype=int)
print(x)

#create a numpy array of ones
y=np.ones((4,5),dtype=int)
print(y)

#create an array of particular value
z=np.full((2,3),5)
print(z)

#create an array of identity matrix
a=np.eye(4)
print(a)

#create a numpy array of random values
b=np.random.random((3,4))
print(b)

#create a random intiger values array with specific range:
c=np.random.randint(5,50,(4,3))
print(c)

#array of evenly spaced values--->specifying the no. of values required
d=np.linspace(10,30,5)
print(d)

#convert list to numpy array
list_2=[1,2,3,4,5]
np_array=np.asarray(list_2)
print(list_2)
#type(list_2)
print(np_array)
type(np_array)

c=np.random.randint(19,90,(3,4))
print(c)
print(c.shape)  #row and column
print(c.ndim)   #dimention of array
print(c.size)   #number of element in an array
print(c.dtype)  #checking data type of the values in the array

"""#Mathematical operation on a np array"""

a=np.random.randint(10,100,(3,4))
b=np.random.randint(5,50,(3,4))
print(a)
print(b)
#print(a+b)
#print(a-b)
#print(a*b)
#print(a/b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

"""#Array Manipulation

"""

#create transpose
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
trans=np.transpose(array)
print(trans)
print(trans.shape)

#create transpose (second method)
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
trans2=array.T
print(trans2)
print(trans.shape)

#reshape a array
a=np.random.randint(0,100,(2,3))
print(a)
print(a.shape)
b=a.reshape(3,2)
print(b)
print(b.shape)

