# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-ovHSXAgDyww1agk_IzhuucWA_MVLSh

#Factorial of a number
"""

num = int(input("enter a number to find its factorial: "))
factorial = 1
if num == 0:
  print("factorial of 0 is 1.")
else:
  for i in range (1,num+1):
    factorial=factorial*i
  print("The factorial of", num, "is",factorial)

#Factorial of a number using function

def factorial_value(n):

  if n==0:
    return 1
  return n*factorial_value(n-1)
result= factorial_value(5)
print(result)

#Factorial of a number using function

def factorial_value(n):

  if n==0:
    return 1
  return n*factorial_value(n-1)
result= factorial_value(int(input("enter a number: ")))
print(result)

