# -*- coding: utf-8 -*-
"""Colab_44_data_standardization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-JDfG1ml0U2dtdZuwwwg3eG53d_nuqXR

#Data Preprocessing Tech.
"""

import numpy as np
import pandas as pd
import sklearn.datasets

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#loading the dataset (breast_cancer dataset)
dataset = sklearn.datasets.load_breast_cancer()
print(dataset)

#loading the data to a pandas DataFrame
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head()

df.shape

x=df
y=dataset.target
print(x)

print(y)

#spliting the data into training and testing dataset
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=3)

print(x.shape,x_train.shape,x_test.shape)

#standardized the data
print(dataset.data.std())

scaler=StandardScaler()
scaler.fit(x_train)
x_train_standardized = scaler.transform(x_train)
print(x_train_standardized)

print(x_train_standardized.std())

x_test_standardized = scaler.transform(x_test)
print(x_test_standardized)

print(x_test_standardized.std())

