# -*- coding: utf-8 -*-
"""colab_basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Np45hYT_-IQEifEKICrXYt3w6QHt2Xfk
"""

print("hello")

import pandas as pd

#df=pd.read_csv('/content/sample_data/mnist_train_small.csv')

#df.head()

"""#print function"""

print("hello")

print("hello"+' Worlds')

print(8+5)



"""# variable and constant"""

Super_Hero="Iron Man"
print(Super_Hero)

Super_Hero="Captain America"
print(Super_Hero)

Hero1, Hero2, Hero3 = "Iron Man", "Captain America", "Bat Man"
print(Hero1)
print(Hero2)
print(Hero3)

x = y = z = 59
print(x)
print(y)
print(z)



"""#Input Function"""

number_1 = input("Enter the first number: ")
number_2 = input("Enter the second number: ")

sum = number_1+number_2
print(sum)

number_1=int(input("Enter the first number: "))
number_2=int(input("Enter the second number: "))
sum=number_1+number_2
print(sum)

#chnaging the data types in python
x=5
type(5)

print(float(x))

