# -*- coding: utf-8 -*-
"""colab_seaborn_library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_NcdPUiIOYOSsVf7BEWHyXQz6V1p7Uk

#Seaborn library
-->Data visualization library(use in ML for large data plotting)
"""

#Importing the library
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#seaborn as some built-in datasets
#total bill vs tips datasets
tips=sns.load_dataset('tips')
tips.head()

#visualize the data
sns.relplot(data=tips,x="total_bill",y="tip",col="time",hue="smoker",style="smoker",size="size")

#setting a theme for plot
sns.set_theme()

#load the iris dataset
iris=sns.load_dataset('iris')
iris.head()

#Scatter plot 
sns.scatterplot(x="sepal_length",y="petal_width",hue="species",data=iris)

sns.scatterplot(x="sepal_width",y="petal_length",hue="species",data=iris)

#loading titanic datasets
titanic=sns.load_dataset('titanic')
titanic.head()

#count plot
sns.countplot(x="class",data=titanic)

titanic.shape

sns.countplot(x="survived",data=titanic)

#Bar Plot
sns.barplot(x='sex',y='survived',hue='class',data=titanic)

#house price dataset(not in-built data set so we import if from the sklearn library)
#import from sklearn lib
from sklearn.datasets import load_boston
house_boston=load_boston()
print(house_boston)

house=pd.DataFrame(house_boston.data,columns=house_boston.feature_names)
house['PRICE']=house_boston.target
house.head()

#Distribution plot
sns.distplot(house['PRICE'])

#Correlation Matrix
#constructing a heat map
correlation=house.corr()
plt.figure(figsize=(10,10))
sns.heatmap(correlation,cbar=True,square=True,fmt='.1f',annot=True,annot_kws={'size':8},cmap='Blues')

